### ISSUE TITLE
`fetchSCAN` upgrades

### ISSUE THREAD

**Issue by brownag** [ncss-tech/soilDB#184]
- [x] handle error on timeout etc. gracefully and check other error handling logic is applied consistently (empty objects, try-error result)
- [x] refactor code involving `melt` `ddply` etc #161
- [ ] consider optimizations for requests to [AWDB (Air-Water Database) Web Service](https://www.nrcs.usda.gov/wps/portal/wcc/home/dataaccess/helpCenters/!ut/p/z1/rZJNb8IwDIb_Sjn0WNm0KUmPXQ-DFQkxYKW5TCEY2q1fQES3f7-CdtkBuknzzcpr57Ufg4Q1yEqd870yeV2postTOXoVImLDGcMpiomL82ges5mPHsYMkqtg4opwLBYYP0aMYRhEfDldcIyXI5C_qccbEWJf_QtIkLoyjckgbbW2dF0ZqoyNWV2SjVtllKW0ptPJyqhobGxpY53oeM41_Uiuz5dujc63kHKXcaE9cgQn32E7NXRUQBsHA-4HjCka0ebb_R178v5wyeW_nvmvglsLfugTdATSziS_bZJDcs6phVVVH8sO-eKPOxgjPPVR6s4ofzscZNixuvD5MLD-B1hNuVqVwvt03p9Fu9xlxX4w-AKbGhVs/dz/d5/L2dBISEvZ0FBIS9nQSEh/)
- [ ] address multiple sensors #14
- [x] Add support for alternate time intervals (e.g. `'hourly'`) and other custom parameters in batch interface (#260)
- [x] Add StationMetadata.stationDataTimeZone to SCAN_SNOTEL_metadata object
- [x] Add support for SNOWLITE stations

**Comment by brownag** [comment]
A note that now with explicit support for hourly data we should be able to put those data into correct timezone to make accurate datetime objects for data from across multiple timezones. 

The StationMetadata should include `stationDataTimeZone ` attribute which can be added to cached `SCAN_SNOTEL_metadata` data object in the package rather than queried on the fly. This value can be used inside the fetchSCAN internal methods for conversion of each sensor time series within a site

<html>
<body>


stationDataTimeZone | BigDecimal | The time zone in which the station collects data.
-- | -- | --



</body>
</html>

**Comment by dylanbeaudette** [comment]
An example:

```
https://wcc.sc.egov.usda.gov/reportGenerator/view_csv/customSingleStationReport,metric/daily/XXXX:CA:SCAN/%7Cid=%22%22%7Cname/POR_BEGIN,POR_END/WTEQ::value,PREC::value,TMAX::value,TMIN::value,TAVG::value,PRCP::value
```

**Comment by dylanbeaudette** [comment]
Sufficiently addressed by merge of #357, will open a new issue (#358) for user-defined TZ. Multiple sensors addressed in own issue.
